### ISSUE TITLE
Feature request: Reference guided correction - locally

### ISSUE THREAD

**Issue by rahulvrane** [DecodeGenetics/Ratatosk#14]
Hi
I was wondering if we are able to run ref guided correction locally. I do have access to required CPU #'s and RAM on 1 single machine.. 

Thanks a ton
Cheers

**Comment by philres** [comment]
I second that. Would be great to have that!

**Comment by philres** [comment]
Also, would be happy to do some testing if that'd help.

**Comment by GuillaumeHolley** [comment]
Sure, I will try to make something with GNU Parallel :) I'll keep the issue open until this is online.

**Comment by philres** [comment]
Nice, thanks!

**Comment by GuillaumeHolley** [comment]
Hi @rahulvrane and @philres ,

I just pushed a script to run Ratatosk with the reference-guiding on a single-machine (turns out that GNU Parallel wasn't needed after all). README was updated. It works but hasn't been tested thoroughly so I would appreciate any feedbacks and suggestions.

Guillaume

**Comment by GuillaumeHolley** [comment]
Also, I'll be pushing the v0.3 of Ratatosk next week. It comes with a new key feature for the reference-guiding that I'll keep as a surprise for now :)

**Comment by philres** [comment]
Awesome, thanks will give it a go!

Philipp

**Comment by rahulvrane** [comment]
Epic - thanks for that! I'll give this a swirl and keenly await 0.3! 
Cheers
Rahul

**Comment by jelber2** [comment]
If one has a lot of bins (say >2000) because the reference genome has a lot of small scaffolds, but scaffold L50 is say ~10 (for a mammalian genome), would you recommend using the GNU Parallel implementation of the local reference guided correction code? I have been running `Ratatosk_SingleNode.sh` from commit 74ca617 with 30 cores, and I think it is about half way done after 1 day of computing. On that note, maybe you could provide a option for using GNU Parallel in a new commit of `Ratatosk_SingleNode.sh` through an `if/elif` statement. I understand that would certainly increase the memory usage.
