### ISSUE TITLE
Ratatosk in de novo or reference mode

### ISSUE THREAD

**Issue by jelber2** [DecodeGenetics/Ratatosk#16]
Hi,

If one de novo assembles paired-end Illumina reads with say ABySS and then uses Ratatosk on the ABySS assembly as a reference, does this equate to a faster but perhaps less accurate de novo Ratatosk method?

**Comment by GuillaumeHolley** [comment]
Hello @jelber2,

As far as I remember, ABySS produces (like many assemblers) mixed-haplotype assemblies so by doing this, Ratatosk will produce reads which are also mixed-haplotypes.

Also, Ratatosk was designed specifically for short reads in input. First step of the graph construction is to remove all k-mers with less than 2 occurrences in the input data sets so it wouldn't work with an assembly in input. Even if you input twice your assembly, I think there exists some assembly- and/or mapping- based methods which could be more adapted to this input.

**Comment by jelber2** [comment]
Perhaps I don’t understand the usage of the  Ratatosk_SingleNode.sh script? That would be used if one has a good quality reference before hand and short and long reads from the individual as the reference?

**Comment by GuillaumeHolley** [comment]
My apologies, I misunderstood your initial question and thought you wanted to replace the input short reads with an assembly. Now that I understand correctly your question, I'm still not sure it would work great. Or maybe not "better" than using a reference genome, very likely not faster. The problem is that your short read assembly would have short N50, a fragmented assembly basically. In such case, it is unclear how to bin long reads that overlap two or more contigs from the assembly. Best scenario is that the primary alignment MAPQ of a long read overlapping 2+ contigs drops below 30: the long read ends up in the ambiguous bin and is corrected using all short reads. Worst case is that the long read is binned with one of the contigs it overlaps and can only be partially corrected using the short reads which map to this contig as well.

**Comment by jelber2** [comment]
Ok. This makes sense to me.
