### ISSUE TITLE
Advice and request on genome-guided polishing with BAM files

### ISSUE THREAD

**Issue by andreaswallberg** [DecodeGenetics/Ratatosk#19]
Dear developers,

We are working on a large dataset (600Gbp / 84 million long-reads and 3 billion short-read pairs) for a large, fragmented and repetitive genome assembly (data described in more detail in issue #18 ), consisting of some couple of hundreds of thousands of contigs/scaffolds and about 83 M unmapped short-reads. Naturally, this is a very difficult genome and dataset.

I am trying out the genome-guided approach which starts from BAM files and initial polished long-reads (upper) look very interesting and clean compared to raw reads (lower):

![image(1)](https://user-images.githubusercontent.com/1176066/99421171-64084580-28fe-11eb-97f4-6e290dcba6a8.png)

I have two questions and potential requests:

1. Before the polishing starts, Ratatosk (or rather, one of the scripts/programs in the wrapper Ratatosk_SingleNode.sh) one pair of uncompressed long-read and short-read fasta files for every contig. In our case this results in a huge set of uncompressed sequence on disk.

Is it possible make the script in question generate gzip-compressed fasta files instead of uncompressed ones?

2. It appears to be the case that after each round of polishing long-reads using the short-reads associated with every contig, Ratatosk checks the full set of 84M unmapped short-reads. This makes it extremely slow for us.

Is it possible to suppress the use of unmapped short-reads for this polishing step? Alternatively, possibly run an "afterburn" where those reads are applied only once to all long-reads in one go? Does discarding unmapped reads invalidate the error correction?

3. My run will time out. If I restart the genome-guided error correction, will it reuse the large set of fasta files already generated on the disks or will it re-generate them regardless?

**Comment by GuillaumeHolley** [comment]
Dear @andreaswallberg,

1. Yes, I suppose it is possible. I am working on a major refactor of Ratatosk so that feature would probably come with the release of this new Ratatosk version.
2. Ratatosk works on the more or less relaxed assumption that there is **no** short read coverage gap for the region of the genome you are trying to correct. Such a gap usually occurs when correcting a long insertion or a difficult to map region. For such a gap, the short reads that should cover this gap usually end up unmapped. Now, if the unmapped reads are missing and you do have coverage gaps in your input short reads, Ratatosk might over-correct the input long reads. In particular, it might correct the long reads regions overlapping the gaps with incorrect subsequences that look similar enough. So to answer your question: Yes, you can remove the the unmapped reads from the correction of each bin but you might end up with some over-correction. With 3 billion mapped short reads and only 84 million unmapped one, I guess it is a risk you might want to take. I can also have the option ready for the next release.
3. Everything will be re-generated.

In general, I would **not** recommend the reference-guided assembly for your reads since your reference is fragmented. Any long read overlapping 2+ contigs will only be correct with the short reads of one of the contigs.
