### ISSUE TITLE
non-{A,C,G,T} characters appearing in the corrected reads

### ISSUE THREAD

**Issue by ASLeonard** [DecodeGenetics/Ratatosk#26]
Hi,
After finishing the corrected of reference-guided reads, I noticed that many "invalid" characters have been introduced that are problematic for downstream analysis. The only reference I noticed to nonstandard bases is in the readme, where they are not used in correction. 

I found some code in Alignment.C where ambiguity is handled, but it isn't clear to me if it is expected that Ratatosk outputs other bases (K,Y,N,V,M,D,W...), or if these should have been resolved during processing.

There may be more fine-tune ways of resolving ambiguous bases, but filtering out via something like seqtk rejects 90% of ratatosk corrected reads, which makes the output not useful.

**Comment by GuillaumeHolley** [comment]
Hi @ASLeonard,

The latest version of Ratatosk introduces these IUPAC ambiguity symbols when there is uncertainty about what the correction should be in case Ratatosk detects that the corrected sequence contains a SNP candidate. An example is when the raw read has an erroneous deletion where the "real" sequence actually contains a symbol which could be from a SNP. In that case, Ratatosk sees that there is potentially a SNP but cannot tell which of the possible alleles is the correct one (because the raw sequence is deleted) and hence, it outputs all the candidate allele symbols for that position under the form of a IUPAC ambiguity character. Older versions of Ratatosk were simply writing the "best guess" among the candidates but it turns out to be a very weak strategy when the correction wasn't too confident and this was introducing too many false positives.

I have a new version of Ratatosk which should reduce the number of these ambiguity symbols by simply better detecting which positions in the graph are SNP candidates. But this won't remove the ambiguity symbols, just reduce their number.

**Comment by ASLeonard** [comment]
Okay, glad to know it isn't something unexpected.

It sounds like the "correction" being applied is essentially inserting a (potentially ambiguous) base to where the raw read had a deletion. Would it then make sense to just remove any ambiguous base, partially undoing the "correction", if the other analyses can't process them? Maybe it would be a decent optional argument to have such behaviour. I read that some people just replace any ambiguous bases with *A*, but that seems more harmful than just not trying to fix an erroneous deletion.

**Comment by GuillaumeHolley** [comment]
I don't think there is an optimal strategy here if you downstream analysis doesn't work with ambiguity symbols. Removing the symbols would be mostly the same as having deletion errors in your read which I guess it not a bad idea.  But instead, I would probably replace the ambiguity symbols with random characters which is what the assembler Flye does. This would be mostly the same as having substitution errors at that location but at least, you keep the length of the read intact.
Something else you can do is reference-based polishing: if at some position on your ref genome, you see only reads with either the ref allele symbol or an ambiguity symbol (so there is no evidence for a SNP), it's probably safe enough to replace all ambiguity symbols at that position with the ref allele symbol.

**Comment by ASLeonard** [comment]
I'm already using the reference-guided mode of Ratatosk, so I guess there is read support for an SNP.

The flye suggestion is useful. I'm pretty new to these ambiguity codes, but it seems it should be appropriate to randomly select from the set of possible bases, and maintaining length/alignment for assembly is probably more important and post-polishing may fix it anyway.

**Comment by GuillaumeHolley** [comment]
Just as a side note, I am now providing a script in `scripts/replaceIUPAC.py` to replace these characters by random {A,C,G,T} characters.
