### ISSUE TITLE
Correction Nanopore reads using PacBio HiFi reads?

### ISSUE THREAD

**Issue by jflot** [DecodeGenetics/Ratatosk#29]
Hello, I am thinking to try Ratatosk to correct Nanopore reads using PacBio HiFi reads. Is there any specific setting I should use for that, or can I just input the PacBio HiFi reads as if they were Illumina single reads?

**Comment by GuillaumeHolley** [comment]
Hi @jflot,

Thanks for your interest in Ratatosk. As you know, Ratatosk was designed for short reads input and I have never tried it with PacBio Hifi reads. It shouldn't be an issue but some steps might need to be modified/adjusted. For example, some steps during the index construction are specifically designed for short reads so they will probably take longer to run with longer reads.
Anyway, I think a good start would be to use the parameter `-i` (insert size) with something like 1000 to 2000 instead of the default 500 (this will most likely increase the running time but the correction will take advantage of the longer length of the reads). Also, use `-w` with 10000 instead of the default 1000. Let me know how it goes, I can change some parts to make it work better with your input.

PS: I am most likely going to push this week a new version of ratatosk that should improve the correction compare to the current version.
