### ISSUE TITLE
Run time estimation

### ISSUE THREAD

**Issue by Akazhiel** [DecodeGenetics/Ratatosk#35]
Hello!

What is the run time estimation for the correction of the long reads? I used the default command for running Ratatosk `Ratatosk correct -v -c 90 -s short_reads.fastq -l long_reads.fastq -o out_long_reads` and it's been running for 6 days now on a computing server. We don't have multiple nodes on the server so I'm running it on single node mode but I wouldn't have expected it to run for this long. At the moment is in this step `Ratatosk::addCoverage(): Subsampling reads`. How more would you say it can take?

Best regards,

Jonatan

**Comment by GuillaumeHolley** [comment]
Hi @Akazhiel,

Ratatosk's running time is mostly proportional to how many reads you want to correct, so basically coverage. It also depends on the complexity of the genome the reads are from: reads containing a lot of repeats are expected to take longer to correct. So without a genome size and coverage estimation, it is impossible for me to say how long this is gonna take. 80x of ONT reads for a 3.2 Gbp human genome should be currently around 6000 to 7000 CPU hours. Next Ratatosk version should get this below 4000 CPU hours.

That being said, Ratatosk is a 2-rounds correction process: Each round builds an index and use that index to correct the long reads. Step `Ratatosk::addCoverage(): Subsampling reads` indicates that you are at the end of the indexing part of one of the 2 rounds. I am hopeful that after 6 days, this is the indexing part of the 2nd round. The correction in the second round is also usually a lot faster than in the first round.

**Comment by Akazhiel** [comment]
Hello,

Thanks for the quick reply. I also hope it's the 2nd round that is doing now although I'm not so sure. Our coverage on the long reads I believe is close to 30x, but the coverage of the short reads is unknown since it wasn't mapped and I couldn't find any data about it. The fastq is 254Gb compressed but that hardly tells us something. It is human data. I'd guess the run time is also affected by the coverage of the short reads that are being used to correct?

Really looking forward to the improvements in the next version!

Cheers,
Jonatan

**Comment by GuillaumeHolley** [comment]
Well it's hard to say from a compressed FASTQ file but I think a rough estimate of 50x to 90x coverage (ballpark) seem reasonable here, nothing that Ratatosk cannot handle. As you said, more short reads there are and technically more time we spend on index construction and read correction. This is why internally, the short reads are downsampled anyway because even 50x would be too much data to add in the graph. Obviously, more short reads there are and more time we spend in the index construction step since it takes more time to downsample.

Most main steps in the output are suffixed with either `(1/2)` or `(2/2)` to indicate which round you're at. In case you cannot see that, you can also have a look at the output files. Look for a file with suffix `.2.fastq`: if this file exists and its last modification is at least a couple of hours old, then it means you are in the second round of correction.

My plan is to push the next version of Ratatosk some time next week, just to make sure everything is in order.

**Comment by Akazhiel** [comment]
The only output files I have for now are the `H2009_corrected.index.k63.fasta` which I'd assume is the index the program generates. Then I have `H2009_corrected.2.pids.1` and a couple minutes ago this other one popped up `H2009_corrected.2.pids.2` but is empty for now. Does this mean is just starting the 2nd round of correction?

**Comment by GuillaumeHolley** [comment]
If those are the only output files you have, it means that you are still in the first round of correction. As a matter of fact, you are still constructing the index of the first round of correction so no correction has started yet. This is clearly not good and unusual and I would like to look into it, see what is the issue. For HG002, 60x short reads + 80x ONT, I think index construction is about 1500 CPU hours for the first round so 6 days with 90 cores is way too much. Can you share the following with me?

1. The output log of Ratatosk currently in your terminal. This should contain some useful info that can help me with pinpoint what steps is struggling
2. The input data (short and long reads)

**Comment by Akazhiel** [comment]
Hello, the current output log in the terminal is the following:
```
Ratatosk::addCoverage(): Processed 3593000000 reads.
Ratatosk::addCoverage(): Processed 3594000000 reads.
Ratatosk::addCoverage(): Processed 3595000000 reads.
Ratatosk::addCoverage(): Processed 3596000000 reads.
Ratatosk::addCoverage(): Processed 3597000000 reads.
Ratatosk::addCoverage(): Processed 3598000000 reads.
Ratatosk::addCoverage(): Processed 3599000000 reads.
Ratatosk::addCoverage(): Processed 3600000000 reads.
Ratatosk::addCoverage(): Processed 3601000000 reads.
Ratatosk::addCoverage(): Processed 3602000000 reads.
Ratatosk::addCoverage(): Processed 3603000000 reads.
Ratatosk::addCoverage(): Processed 3604000000 reads.
Ratatosk::addCoverage(): Processed 3605000000 reads.
Ratatosk::addCoverage(): Processed 3606000000 reads.
Ratatosk::addCoverage(): Processed 3607000000 reads.
Ratatosk::addCoverage(): Processed 3608000000 reads.
Ratatosk::addCoverage(): Processed 3609000000 reads.
Ratatosk::addCoverage(): Processed 3610000000 reads.
Ratatosk::addCoverage(): Processed 3611000000 reads.
Ratatosk::addCoverage(): Processed 3612000000 reads.
Ratatosk::addCoverage(): Processed 3613000000 reads.
Ratatosk::addCoverage(): Processed 3614000000 reads.
Ratatosk::addCoverage(): Processed 3615000000 reads.
Ratatosk::addCoverage(): Processed 3616000000 reads.
Ratatosk::addCoverage(): Processed 3617000000 reads.
Ratatosk::addCoverage(): Processed 3618000000 reads.
Ratatosk::addCoverage(): Processed 3619000000 reads.
Ratatosk::addCoverage(): Processed 3620000000 reads.
Ratatosk::addCoverage(): Processed 3621000000 reads.
Ratatosk::addCoverage(): Processed 3622000000 reads.
Ratatosk::addCoverage(): Processed 3623000000 reads.
Ratatosk::addCoverage(): Collecting branching information.
Ratatosk::addCoverage(): Subsampling reads.
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [9, 42[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [42, 84[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [84, 102[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [102, 113[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [113, 122[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [122, 135[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [135, 154[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [154, 174[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [174, 203[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [203, 261[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [261, 372[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [372, 683[
Ratatosk::addCoverage(): Subsampling reads (0.0609756) coloring vertices with k-mer coverage [683, 194226923[
Ratatosk::addCoverage(): Compacting subsampled reads.
Ratatosk::addCoverage(): Coloring graph with subsampled reads.
```

And the data was downloaded from the SRA. Here the [Nanopore](https://www.ncbi.nlm.nih.gov/sra/DRX248308[accn]) and here the [Illumina](https://www.ncbi.nlm.nih.gov/sra/DRX249889[accn]) reads.

Also as of now, it's been 4576 CPU hours.

**Comment by GuillaumeHolley** [comment]
It seems I have underestimated the compression ratio in my previous coverage estimate (to be fair, I didn't know it was SRA compression either). From the output, I see that you have about 3.6 billion short reads which should be a 170x coverage data set. This is a **lot** of short reads so it comes to me at no surprise that the index construction takes such a long time. You even have a 31-mer in the graph which alone occurs in about 194 million reads. Given that 60x short reads required 1500 CPU hours, having at least 4500 CPU hours for the index construction does make sense to me now.

It might seem to be a lot of time spent into downsampling reads but Ratatosk does not do "completely" random downsampling. We instead select randomly reads from unitigs with different ranges of coverage in order to cover as many paths as possible with the downsampled set. This might actually be really important since the reads are from a study of somatic SVs in cancer genomes (which explains the really high coverage).

The good point now is that the downsampling is finished and Ratatosk will work from now on with the downsampled reads only. You still have the detection of SNP and STR candidates left for the index construction but this should be fast enough. The "bad" point is that I imagine you have submitted this as a job to your cluster with a time limit. And you already used 6 days on this limit. How much time do you have left before the job gets canceled?

**Comment by Akazhiel** [comment]
We are actually using this data because we are trying to predict SV from Nanopore data with base-pair resolution to predict putative neoantigens. 

For your question, I am working on a cluster but since it hasn't been fully implemented yet I am running Ratatosk inside and interactive Docker container which means there is not a time limit. I'm only limited if my sysadmin needs to restart the server for whatever reason.

For the future I'll probably take the 2-step approach in the case it needs to be stopped so I don't lose everything.

**Comment by GuillaumeHolley** [comment]
As of now, you just need to complete the 1st round of correction to not loose everything. The 1st round of correction should produce a file named `H2009_corrected.2.fastq` which are the reads corrected by the short reads. You already have the file named `H2009_corrected.index.k63.fasta` which is the graph for the second round of correction. Those 2 files are the only ones you need to build the full index for round 2 because the short reads won't be used anymore from that point. Note that because only the long reads are used in round 2 and your ONT dataset is only 30x, this should go a lot faster than round 1.

Could you let me know how things are progressing beginning of next week?

**Comment by GuillaumeHolley** [comment]
Also make sure you have the latest Ratatosk version.

**Comment by Akazhiel** [comment]
Yes, I will keep you updated on how it goes. And yes, the version I'm running was installed by cloning the git repo 6 days ago right before running it.

**Comment by Akazhiel** [comment]
Hi @GuillaumeHolley,

Quick update on how it is going. It has almost generated the `H2009_corrected.2.fastq` file, it's at 87Gb now so it should finish this step today hopefully and then will only remain the 2nd correction step.

**Comment by GuillaumeHolley** [comment]
Good to know it is still running and progressing. You have about 11 millions ONT reads to correct so by having a look at the Ratatosk's log or by counting the number of lines in `H2009_corrected.2.fastq` (divided by 4), you can see how much Ratatosk has done.

**Comment by Akazhiel** [comment]
Hello!

I believe it finished completely since this is the last that was printed to the terminal:

```
Ratatosk::correct(): Processed 11125000 reads 
Ratatosk::correct(): Processed 11126000 reads 
Ratatosk::correct(): Processed 11127000 reads 
Ratatosk::correct(): Processed 11128000 reads 
Ratatosk::correct(): Processed 11129000 reads 
Ratatosk::correct(): Processed 11130000 reads 
Ratatosk::correct(): Processed 11131000 reads 
Ratatosk::correct(): Processed 11132000 reads 
Ratatosk::correct(): Processed 11133000 reads 
Ratatosk::correct(): Processed 11134000 reads 
Ratatosk::correct(): Processed 11135000 reads 
Ratatosk::correct(): Processed 11136000 reads 
Ratatosk::correct(): Processed 11137000 reads 
Ratatosk::correct(): Processed 11138000 reads 
Ratatosk::correct(): Processed 11139000 reads 
Ratatosk::correct(): Processed 11140000 reads 
Ratatosk::Ratatosk(): Couldn't remove temporary file
```

And I also have a file called `H2009_corrected.fastq`

**Comment by GuillaumeHolley** [comment]
Hi @Akazhiel,

Glad to know you could complete the run. I'll then close the issue. Don't hesitate to reach out if you have more questions.

Guillaume
