### ISSUE TITLE
Index generation

### ISSUE THREAD

**Issue by Akazhiel** [DecodeGenetics/Ratatosk#38]
Hello!

I'm trying to run the latest version using the four steps method, but when running the first index step, it writes to disk an index file with the name `H2009BL_corrected.index.k63.fasta`. Is this the expected behaviour? I was expecting to have a k31 index file when runnning the first index step with the `Ratatosk index -1` call.

Cheers,

Jonatan

**Comment by GuillaumeHolley** [comment]
Hi @Akazhiel,

Normally, `Ratatosk index -1` should create first a file named `H2009BL_corrected.index.k63.fasta` and then later 2 files named `H2009BL_corrected.index.k31.fasta` and `H2009BL_corrected.index.k31.rtsk`. If the command has completed but those 2 later files are missing, this is not normal behavior indeed. Can you confirm the command has completed without errors and the two files are missing?

Guillaume

**Comment by Akazhiel** [comment]
Hello.

It hasn't finished yet, but I was just wondering why it created first the k63 file since the first index is going to be the k31.

Thanks for the quick reply!

**Comment by GuillaumeHolley** [comment]
No problem.

Ratatosk is a 2-pass correction algorithm: first pass uses a graph with a small k-mer size (k1=31) and second pass uses a large k-mer size (k2=63). For the first pass (k1=31), since it is a small k-mer size, we would want to clean the graph after constructing it. In particular, we would want to clip short tips (unitigs less than 2k bp long that have no successors or predecessors in the graph). Another way to get mostly the same graph after cleaning is to build a first graph G with k2=2*k1 and then builds a second graph G' with k1 **from the unitigs of G**. Obviously, building+cleaning is much faster to do than 2 graphs building but in our case, since we need graph G for the first pass and G' for the second pass anyway, it is more advantageous to do it this way. Hence, indexing is much faster on the second correction pass, You can see that file `H2009BL_corrected.index.k63.fasta` is the input of the command `Ratatosk index -2`.

**Comment by Akazhiel** [comment]
Great, thanks for the useful explanation!

I also have another question if that is okay. If I want to perform multiple corrections, in which step would I have to indicate it? Or do I have to rerun everything on the corrected data? Also, do you recommend performing multiple correction rounds?

**Comment by Akazhiel** [comment]
Yes, I thought there was an option for performing multiple rounds of corrections but maybe I'm confusing it with another software.

**Comment by GuillaumeHolley** [comment]
No you are right, there was an experimental option which was present in previous versions of Ratatosk to run multiple rounds of correction for each read. The idea was to correct first regions of high confidence and steadily progress down such that regions of low confidence would be corrected last but would benefit from the previously corrected regions. Anyway, on the new version of Ratatosk, the gain of using such an option was rather minimal but the running time was increased significantly so I removed the option. I might reintroduce it after more testing.

**Comment by Akazhiel** [comment]
Thanks for the clarification, and for taking your time to explain everything in details. I'll go ahead and close the issue since my doubts have been cleared.

Thank you very much,
Jonatan
