### ISSUE TITLE
Can you run "correct -2" phase without "correct -1"?

### ISSUE THREAD

**Issue by tolarnik** [DecodeGenetics/Ratatosk#39]
Hello, I am using Ratatosk on quite a large dataset. I used simply "correct" without the two-part command system. However, I might run out of resources and I was wondering if it would be possible to run "correct -2" since I believe that the first part of the program is finished.

Do I understand correctly that by running only correct, the program runs "correct -1" and then "correct -2" on its own anyways? And that the "correct -1" command creates "name2.fastq" file while "correct -2" creates "name.fastq" file? And thus if I run "-correct" and I managed to get to the point where "name2.fastq" is created, then it is possible to start from that point on with "correct -2"? 

Thank you very much for your help.

**Comment by GuillaumeHolley** [comment]
Hi @tolarnik,

Thank you for reaching out. The issue was closed so either you figured out the answer or you run actually finished but it is a good question so I am going to reply in case anyone passes through this thread :)

Your understanding is correct: you can run `correct -2` without `correct -1` by following the [two commands guidelines](https://github.com/DecodeGenetics/Ratatosk#single-compute-node---two-steps) in the README. Obviously, you would run only the second command (`correct -2`) assuming that the first one (`correct -1`) has fully completed.  To make sure the first command has completed as intended:
- Make sure a file named `output.2.fastq` has been created (assuming you used `-o output`)
- Make sure `output.2.fastq` has as many lines as your input long read file (`wc -l file.fastq`)

If both requirements are fullfiled, you can keep going with `correct -2`, otherwise you would have to restart the run from scratch. Hope this helps.

Guillaume

**Comment by tolarnik** [comment]
Hello,

thank you very much for your answer! 

Yes, I managed to finish the run in time and so I closed the issue. But thank you nonetheless for your answer! It will be very valuable for me to know this in the future :) 

Have a great day,
Nik
