### ISSUE TITLE
Can I reuse the existing indexes in correction of another long reads?

### ISSUE THREAD

**Issue by asan-emirsaleh** [DecodeGenetics/Ratatosk#43]
Hi @GuillaumeHolley 
I have corrected LongReads1 with PE_reads1. Can use .index.k31.* and .index.k63.* files for correction of another set of reads (LongReads2)? Is there another way to reuse existing files?

Best regards
Asan

**Comment by GuillaumeHolley** [comment]
Hi @asan-emirsaleh,

In short, you can use the files with suffix `.1.index.k31.*` to correct LongReads2 but you cannot use the files with suffix `.2.index.k31.*`. Indeed you will have to reconstruct the latter for each long read set you want to correct. Keep in mind that it is much faster to build the second index than the first one so it is not really a bottleneck.

In detail, the files with suffix `.1.index.k31.*` are the index of the first correction pass and the index is built entirely from the short reads. The only reason the long reads are supplied to the index building 1 is in case you build the index for a subset of the short reads extracted from a BAM file (so mapping a specific region/loci). In that case, you can supply unmapped short reads and the long reads would be used to help choosing which unmapped short reads to use because there can be a lot of unmapped short reads which are garbage. However, if you use all short reads (for genome wide correction), long reads are not used at all for the first index building. For the second index building, the long reads corrected during the first correction step are mapped back to the graph built from the short reads. So technically, the second correction pass is a hybrid short and long reads correction. If you were to reuse the second index of LongReads1 to correct LongReads2, it would mean that variants private to LongReads1 would be used to correct LongReads2. Similarly, variants private to LongReads2 would be considered as errors given that they do not occur in LongReads1.

Best,
Guillaume

**Comment by asan-emirsaleh** [comment]
Thank you for explanation. It was helpful for me.

Best regards
Asan
