### ISSUE TITLE
/usr/local/bin/Ratatosk Permission denied

### ISSUE THREAD

**Issue by kangxiongbin** [DecodeGenetics/Ratatosk#46]
Dear someone,
I don't have roof permission, how to install ratatosk?

 make install
[ 44%] Built target bifrost_lib
[100%] Built target Ratatosk
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/Ratatosk
CMake Error at src/cmake_install.cmake:52 (file):
  file INSTALL cannot copy file
  "/prj/hybrid-assembly/kang/software/ratatosk2/Ratatosk/build/src/Ratatosk"
  to "/usr/local/bin/Ratatosk": Permission denied.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)
make: *** [Makefile:105: install] Error 1

**Did I already install it in the path** /prj/hybrid-assembly/kang/software/ratatosk2/Ratatosk/build/src/Ratatosk? 

Best regards,
Xiongbin

**Comment by GuillaumeHolley** [comment]
Dear @kangxiongbin,

As mentioned in the README, if you do not have root permissions, you must install Ratatosk in a directory where you know you do not need root permissions:
```
cmake -DCMAKE_INSTALL_PREFIX=/some/path/ ..
make
make install
```
where `/some/path/` is a directory you own which does not require sudo permission. Once you are done with these steps, make sure you add `/some/path/` to your path (`export PATH=$PATH:/some/path/`), otherwise your system won't be able to know where to look for the Ratatosk binary. 

The path `/prj/hybrid-assembly/kang/software/ratatosk2/Ratatosk/build/src/Ratatosk` is where Ratatosk was compiled after `make` and before `make install`. You can just as well call Ratatosk from there.

**Comment by kangxiongbin** [comment]
Thank you very much!
