### ISSUE TITLE
Parallel thread segmentation fault

### ISSUE THREAD

**Issue by Chullcrew** [DecodeGenetics/Ratatosk#52]
Hello,

I am attempting to clean up nanopore reads for a haploid fungal nanopore dataset. I am able to run the command without the -c flag which I allowed to run for 18 days between semesters. CPU usage remained in the single digit percentage while it was being monitored.

Attempting to improve performance by adding -c # with any argument other than 1 causes the command to fail. After the first correction step "`Ratatosk::Ratatosk(): Correcting long reads (1/2)`" I am given the following error message "`zsh: segmentation fault  ratatosk correct -v -c 2 -Q 90 -G -s -l barcode02_porechop_NoMito.fastq -o`".

I can't reasonably wait for the single thread version of the command to run for an indeterminant amount of time, and I am confident the computer I am using has plenty of resources to run multiple threads (128GB ram, Apple M@ Ultra, Sonoma14.5, 2TB drive). Is there some way to resolve this error?

For reference, my organism's genome is approximately 43Mb. The nanopore dataset is 1.7GB (1.15Gb,~26x coverage), and my illumina paired end data is 6.25GB each (1.8Gb, ~43x coverage). My full command is as follows: `ratatosk correct -v -c 2 -Q 90 -G -s pairedend1.fastq.gz pairdend2.fastq.gz -l barcode02 barcode02_porechop_NoMito.fastq -o outfilename.fasq.gz`. I have also tried the command with uncompressed illumina reads with the same results.

Any suggestions would be appreciated.

**Comment by Chullcrew** [comment]
Follow up, this occurs even with much smaller nanopore data sets.

**Comment by GuillaumeHolley** [comment]
Hi @Chullcrew,

Sorry for the late answer. The first obvious problem here is the segfault as soon as you use multiple threads regardless of your input. There might be a second problem here which is 18+ days running time in single thread for a seemingly small input dataset which seems way too long. I use regularly Ratatosk on different Unix machines so I doubt a "big" bug like this would be in the code since everything works well for me. You do have plenty of RAM and threads available on your machine.
I think the problem here is that you run Ratatosk on an Apple M@ Ultra which is based on an ARM architecture. Ratatosk was originally designed on and for x86 architectures. It was never tested on CPUs other than the Intel ones for MacOS. I am not even sure how you managed to install it on Mac with an Apple Silicon CPU. May I ask which version of Ratatosk you use and how did you install it?

**Comment by Chullcrew** [comment]
Thank you for the response.

I thought that might be the case. I'm going to try installing it on another older Mac in our lab, and see what results I can get. I will follow up with a reply one way or the other.

As for the installation, I did encounter an error attempting to install from the Bioconda channel where I usually get bioinformatic software. That is a sporadic issue though, so I just used the standard cmake installation instructions on the main page. It seemed to install without issue.

**Comment by Chullcrew** [comment]
Installing and running ratatosk on a different computer worked. This one was an intel i7 processor, so I believe the chip architecture was indeed the problem.

For the record, the bioconda installation failed on the other computer as well, so I used the same cmake install. Not sure why it isn't pulling from that channel correctly, but it's not really an issue.

Regardless, I'm marking the issue closed. Thank you for your assistance.
